<?php

$language_array = array(
0 => "Anglo-Norman",
1 => "Arabic",
2 => "Azestan",
3 => "Chinese",
4 => "Cornish",
5 => "Czech",
6 => "Dutch",
7 => "English - Anglo-Saxon / Old English",
8 => "English - Middle English",
9 => "English - Scots",
10 => "Ethiopian",
11 => "French - Breton",
12 => "French - Gascon",
13 => "French - Old French",
14 => "French - Other",
15 => "French - Provencal",
16 => "German",
17 => "German - Middle High German",
18 => "Greek",
19 => "Hebrew",
20 => "Italian",
21 => "Latin",
22 => "Manx",
23 => "Old Norse",
24 => "Old/Middle Irish",
25 => "Other",
26 => "Pahlavi",
27 => "Pazand",
28 => "Persian",
29 => "Portuguese",
30 => "Russian",
31 => "Scottish Gaelic",
32 => "Spanish",
33 => "Spanish - Catalan",
34 => "Spanish - Medieval",
35 => "Turkish",
36 => "Welsh",
);

?>
